CREATE TABLE SPRINT
(
    ID IDENTITY,
    NAME VARCHAR(64),
    START_DATE DATE,
    END_DATE DATE,
    HOLIDAYS INTEGER,
    PTO_TOTAL INTEGER,
    ESTIMATED_POINTS INTEGER,
    COMPLETED_POINTS INTEGER
);